"""
models.py — Pydantic request/response schemas for all API endpoints.

v2: Embeddings are computed client-side (Streamlit) and sent over the wire.
    Backend never loads an embedding model.
"""
from __future__ import annotations

from typing import Any, Optional
from pydantic import BaseModel, Field


# ── /upload_embeddings ────────────────────────────────────────────────────────

class UploadEmbeddingsRequest(BaseModel):
    """
    Client sends pre-computed embeddings alongside chunk metadata.
    embeddings[i] corresponds to chunks[i].
    """
    doc_id: str = Field(..., description="UUID generated by the client")
    filename: str = Field(..., description="Original file name (for display)")
    chunks: list[dict] = Field(
        ...,
        description="List of chunk dicts: {text, page, chunk_index}",
    )
    embeddings: list[list[float]] = Field(
        ...,
        description="(N, dim) float32 embedding matrix as nested list",
    )


class UploadResponse(BaseModel):
    doc_id: str
    filename: str
    chunks_count: int
    message: str = "Document processed successfully"


# ── /ask ─────────────────────────────────────────────────────────────────────

class AskRequest(BaseModel):
    doc_id: str = Field(..., description="Document ID returned by /upload_embeddings")
    question: str = Field(..., min_length=3, description="Natural language question")
    query_embedding: list[list[float]] = Field(
        ...,
        description="Pre-computed query embedding: shape [[...]] (1 × dim), float32, normalized",
    )


class SourceChunk(BaseModel):
    text: str
    page: Optional[int] = None
    chunk_index: int
    similarity: float


class AskResponse(BaseModel):
    answer: str
    confidence: float = Field(..., ge=0.0, le=1.0)
    sources: list[SourceChunk]
    provider: str
    logs: list[str]
    guardrail_triggered: bool = False


# ── /extract ─────────────────────────────────────────────────────────────────

class ExtractRequest(BaseModel):
    doc_id: str = Field(..., description="Document ID returned by /upload_embeddings")


class ShipmentData(BaseModel):
    shipment_id: Optional[str] = None
    shipper: Optional[str] = None
    consignee: Optional[str] = None
    pickup_datetime: Optional[str] = None
    delivery_datetime: Optional[str] = None
    equipment_type: Optional[str] = None
    mode: Optional[str] = None
    rate: Optional[float] = None
    currency: Optional[str] = None
    weight: Optional[str] = None
    carrier_name: Optional[str] = None


class ExtractResponse(BaseModel):
    doc_id: str
    data: ShipmentData
    provider: str
    logs: list[str]
    confidence: float


# ── Internal Pipeline Types ───────────────────────────────────────────────────

class RetrievedChunk(BaseModel):
    text: str
    page: Optional[int] = None
    chunk_index: int
    similarity: float


class LLMResult(BaseModel):
    provider: str
    response: str
    logs: list[str]
